 Project Done By:
## Tanuja Shinde

## About Dataset
The dataset captures customer satisfaction scores for a one-month period at an e-commerce platform called Shopzilla (a pseudonym). It includes various features such as category and sub-category of interaction, customer remarks, survey response date, category, item price, agent details (name, supervisor, manager), and CSAT score etc.

## Dataset Information:

Rows: 85,907

Columns: 20

Usage:

This dataset serves as a valuable resource for conducting Exploratory data analysis (EDA), Visualization, and Machine Learning Classification tasks pertaining to customer service performance evaluation, satisfaction forecasting, and customer behavior analysis within the e-commerce sector.

Do explore pinned 📌 notebook under code section for quick EDA📊 reference
Consider an upvote ^ if you find the dataset useful

## Data Description:

Unique id:	Unique identifier for each record

Channel name:	Name of the customer service channel

Category:	Category of the interaction

Sub-category:	Sub-category of the interaction

Customer Remarks:	Feedback provided by the customer

Order id:	Identifier for the order associated with the interaction

Order date time:	Date and time of the order

Issue reported at:	Timestamp when the issue was reported

Issue responded:	Timestamp when the issue was responded to

Survey response date:	Date of the customer survey response

Customer city:	City of the customer

Product category:	Category of the product

Item price:	Price of the item

Connected handling time:	Time taken to handle the interaction

Agent name:	Name of the customer service agent

Supervisor:	Name of the supervisor

Manager:	Name of the manager

Tenure Bucket:	Bucket categorizing agent tenure

Agent Shift:	Shift timing of the agent

CSAT Score:	Customer Satisfaction (CSAT) score

In [ ]:
#Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import zipfile
from sklearn.preprocessing import FunctionTransformer
import scipy.stats as stats

**Loading data set**

In [ ]:
df=pd.read_csv('/content/eCommerce_Customer_support_data.csv')
df

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85902,505ea5e7-c475-4fac-ac36-1d19a4cb610f,Inbound,Refund Related,Refund Enquiry,NaN,1b5a2b9c-a95f-405f-a42e-5b1b693f3dc9,NaN,30/08/2023 23:20,31/08/2023 07:22,31-Aug-23,NaN,NaN,NaN,NaN,Brandon Leon,Ethan Tan,William Kim,On Job Training,Morning,4
85903,44b38d3f-1523-4182-aba2-72917586647c,Inbound,Order Related,Seller Cancelled Order,Supported team customer executive good,d0e8a817-96d5-4ace-bb82-adec50398e22,NaN,31/08/2023 08:15,31/08/2023 08:17,31-Aug-23,NaN,NaN,NaN,NaN,Linda Foster,Noah Patel,Emily Chen,>90,Morning,5
85904,723bce2c-496c-4aa8-a64b-ca17004528f0,Inbound,Order Related,Order status enquiry,need to improve with proper details.,bdefe788-ccec-4eda-8ca4-51045e68db8a,NaN,31/08/2023 18:57,31/08/2023 19:02,31-Aug-23,NaN,NaN,NaN,NaN,Kimberly Martinez,Aiden Patel,Olivia Tan,On Job Training,Evening,5
85905,707528ee-6873-4192-bfa9-a491f1c08ab5,Inbound,Feedback,UnProfessional Behaviour,NaN,a031ec28-0c5e-450e-95b2-592342c40bc4,NaN,31/08/2023 19:59,31/08/2023 20:00,31-Aug-23,NaN,NaN,NaN,NaN,Daniel Martin,Olivia Suzuki,Olivia Tan,>90,Morning,4
85906,07c7a878-0d5a-42e0-97ef-de59abec0238,Inbound,Returns,Reverse Pickup Enquiry,NaN,3230db30-f8da-4c44-8636-ec76d1d3d4f3,NaN,31/08/2023 23:36,31/08/2023 23:37,31-Aug-23,NaN,NaN,NaN,NaN,Elizabeth Guerra,Nathan Patel,Jennifer Nguyen,On Job Training,Evening,5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                85907 non-null  object
 1   channel_name             85907 non-null  object
 2   category                 85907 non-null  object
 3   Sub-category             85907 non-null  object
 4   Customer Remarks         28742 non-null  object
 5   Order_id                 67675 non-null  object
 6   order_date_time          17214 non-null  object
 7   Issue_reported at        85907 non-null  object
 8   issue_responded          85907 non-null  object
 9   Survey_response_Date     85907 non-null  object
 10  Customer_City            17079 non-null  object
 11  Product_category         17196 non-null  object
 12  Item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  Agent_name               85907 non-null  object
 15  Supervisor               85907 non-null  object
 16  Manager                  85907 non-null  object
 17  Tenure Bucket            85907 non-null  object
 18  Agent Shift              85907 non-null  object
 19  CSAT Score               85907 non-null  int64
dtypes: float64(2), int64(1), object(17)
memory usage: 13.1+ MB

In [ ]:
df.describe()

          Item_price  connected_handling_time    CSAT Score
count   17206.000000               242.000000  85907.000000
mean     5660.774846               462.400826      4.242157
std     12825.728411               246.295037      1.378903
min         0.000000                 0.000000      1.000000
25%       392.000000               293.000000      4.000000
50%       979.000000               427.000000      5.000000
75%      2699.750000               592.250000      5.000000
max    164999.000000              1986.000000      5.000000

In [ ]:
for i in df.columns:
    print(df[i].value_counts())

Unique id
07c7a878-0d5a-42e0-97ef-de59abec0238    1
7e9ae164-6a8b-4521-a2d4-58f7c9fff13f    1
b07ec1b0-f376-43b6-86df-ec03da3b2e16    1
c0d72065-e4c8-449b-9d55-cadb690b9c54    1
49e1675a-e890-4d27-93a0-51e67a44d86a    1
                                       ..
372b51a5-fa19-4a31-a4b8-a21de117d75e    1
11a3ffd8-1d6b-4806-b198-c60b5934c9bc    1
1cfde5b9-6112-44fc-8f3b-892196137a62    1
ba903143-1e54-406c-b969-46c52f92e5df    1
eb0d3e53-c1ca-42d3-8486-e42c8d622135    1
Name: count, Length: 85907, dtype: int64
channel_name
Inbound    68142
Outcall    14742
Email       3023
Name: count, dtype: int64
category
Returns               44097
Order Related         23215
Refund Related         4550
Product Queries        3692
Shopzilla Related      2792
Payments related       2327
Feedback               2294
Cancellation           2212
Offers & Cashback       480
Others                   99
App/website              84
Onboarding related       65
Name: count, dtype: int64
Sub-category
Reverse Pickup Enquiry              22389
Return request                       8523
Delayed                              7388
Order status enquiry                 6922
Installation/demo                    4116
Fraudulent User                      4108
Product Specific Information         3589
Refund Enquiry                       2665
Wrong                                2597
Missing                              2556
UnProfessional Behaviour             2294
General Enquiry                      1945
Not Needed                           1920
Service Centres Related              1875
Refund Related Issues                1800
Invoice request                      1465
Online Payment Issues                1079
Seller Cancelled Order               1059
Priority delivery                     972
Exchange / Replacement                896
Customer Requested Modifications      805
Payment related Queries               743
Signup Issues                         489
Damaged                               475
Technician Visit                      378
Shopzila Premium Related              361
Return cancellation                   292
Wallet related                        230
Other Cashback                        219
Product related Issues                183
Affiliate Offers                      183
Unable to track                       164
Account updation                      150
PayLater related                      140
COD Refund Details                     85
Shopzilla Rewards                      80
Instant discount                       78
Warranty related                       78
Issues with Shopzilla App              74
Order Verification                     72
Seller onboarding                      62
Service Center - Service Denial        58
Billing Related                        57
Self-Help                              49
Call back request                      46
e-Gift Voucher                         42
Call disconnected                      40
Life Insurance                         23
Other Account Related Issues           22
Card/EMI                               19
Payment pending                        17
Others                                 12
App/website Related                    10
Unable to Login                         7
Commission related                      3
Policy Related                          2
Non Order related                       1
Name: count, dtype: int64
Customer Remarks
Good                                                                                                                                                                                                                                         1390
Good                                                                                                                                                                                                                                         1158
Very good                                                                                                                                                                                                                                     569
Nice                                                                                                                                                                                                                                          316
Thanks                                                                                                                                                                                                                                        276
                                                                                                                                                                                                                                             ...
Please add option to delete order history                                                                                                                                                                                                       1
Me                                                                                                                                                                                                                                              1
Delivery person call back received                                                                                                                                                                                                              1
Worst service and worst customer support executive. They even don\u2019t know what customer was asking about. Simply they will tell the given delivery date. No response for delaying the deliver. Please change the customer executives.       1
For Defect On Arrival scenario it is should be obvious return/replacement. I should not spend time talking to customer service agent for 15-20 mins!                                                                                            1
Name: count, Length: 18231, dtype: int64
Order_id
3230db30-f8da-4c44-8636-ec76d1d3d4f3    1
c27c9bb4-fa36-4140-9f1f-21009254ffdb    1
d406b0c7-ce17-4654-b9de-f08d421254bd    1
c273368d-b961-44cb-beaf-62d6fd6c00d5    1
5aed0059-55a4-4ec6-bb54-97942092020a    1
                                       ..
8153c646-4940-406f-992c-952ed08e9af8    1
9e0d7d55-d012-42f7-8e21-634942419386    1
c1e10375-7426-4b2a-aca6-17dc6bc9c7a3    1
c7d5eef8-d239-474c-8d24-542db2923b3c    1
55bbace3-eb2e-4f67-aacb-4f8ee8512f75    1
Name: count, Length: 67675, dtype: int64
order_date_time
09/08/2023 11:55    7
05/08/2023 20:14    6
08/08/2023 12:51    5
09/08/2023 21:56    5
05/08/2023 20:26    5
                   ..
22/08/2023 21:58    1
29/08/2023 12:28    1
26/07/2023 12:04    1
14/07/2023 22:09    1
20/07/2023 23:03    1
Name: count, Length: 13766, dtype: int64
Issue_reported at
13/08/2023 10:40    13
15/08/2023 10:59    13
06/08/2023 18:22    12
14/08/2023 12:08    12
11/08/2023 19:04    11
                    ..
31/08/2023 12:22     1
31/08/2023 11:20     1
31/08/2023 14:53     1
31/08/2023 03:06     1
31/08/2023 17:55     1
Name: count, Length: 30923, dtype: int64
issue_responded
28/08/2023 00:00    3378
27/08/2023 00:00      21
08/08/2023 17:51      13
17/08/2023 11:34      12
16/08/2023 13:24      12
                    ...
31/08/2023 20:19       1
31/08/2023 16:33       1
31/08/2023 10:58       1
31/08/2023 10:48       1
31/08/2023 20:52       1
Name: count, Length: 30262, dtype: int64
Survey_response_Date
28-Aug-23    3452
27-Aug-23    3379
17-Aug-23    3193
29-Aug-23    3188
07-Aug-23    3014
22-Aug-23    3005
08-Aug-23    3000
26-Aug-23    2990
10-Aug-23    2989
24-Aug-23    2962
23-Aug-23    2944
14-Aug-23    2927
11-Aug-23    2894
16-Aug-23    2885
12-Aug-23    2841
09-Aug-23    2823
15-Aug-23    2819
13-Aug-23    2758
30-Aug-23    2757
18-Aug-23    2605
25-Aug-23    2550
04-Aug-23    2523
21-Aug-23    2510
19-Aug-23    2496
06-Aug-23    2490
03-Aug-23    2467
31-Aug-23    2389
02-Aug-23    2330
05-Aug-23    2283
01-Aug-23    2231
20-Aug-23    2213
Name: count, dtype: int64
Customer_City
HYDERABAD    722
NEW DELHI    688
PUNE         435
MUMBAI       406
BANGALORE    352
            ...
NARAULI        1
AYOOR          1
MUL            1
HOWLI          1
FAIZPUR        1
Name: count, Length: 1782, dtype: int64
Product_category
Electronics                    4706
LifeStyle                      4118
Books & General merchandise    3323
Mobile                         1758
Home                           1328
Home Appliences                1300
Furniture                       471
Affiliates                      166
GiftCard                         26
Name: count, dtype: int64
Item_price
999.0      590
1499.0     326
899.0      309
1299.0     301
799.0      283
          ...
4974.0       1
4065.0       1
3674.0       1
1683.0       1
28500.0      1
Name: count, Length: 2789, dtype: int64
connected_handling_time
299.0    3
301.0    3
418.0    3
282.0    3
368.0    2
        ..
63.0     1
281.0    1
856.0    1
353.0    1
505.0    1
Name: count, Length: 211, dtype: int64
Agent_name
Wendy Taylor         429
Timothy Huff         265
David Smith          264
Jamie Smith          253
Kayla Wilson         216
                    ...
Jackson Brown         20
Alexis Murray         20
Matthew Ross          20
Stephanie Hammond     20
Amy Bell              20
Name: count, Length: 1371, dtype: int64
Supervisor
Carter Park         4273
Elijah Yamaguchi    3855
Zoe Yamamoto        3551
Nathan Patel        3549
Noah Patel          3434
Ava Wong            3373
Emma Park           3290
Mia Patel           3279
Evelyn Kimura       2974
Aiden Patel         2892
Madison Kim         2772
William Park        2692
Scarlett Chen       2676
Emily Yamashita     2581
Jackson Park        2571
Brayden Wong        2540
Logan Lee           2466
Olivia Wang         2233
Abigail Suzuki      2222
Olivia Suzuki       2193
Mason Gupta         2109
Lily Chen           1869
Ethan Tan           1831
Wyatt Kim           1727
Austin Johnson      1723
Sophia Sato         1671
Landon Tanaka       1635
Ethan Nakamura      1584
Jacob Sato          1501
Amelia Tanaka       1364
Alexander Tanaka    1320
Lucas Singh         1285
Dylan Kim           1197
Charlotte Suzuki    1172
Harper Wong         1119
Isabella Wong       1081
Layla Taniguchi      924
Mia Yamamoto         625
Oliver Nguyen        417
Sophia Chen          337
Name: count, dtype: int64
Manager
John Smith         25261
Michael Lee        17600
Jennifer Nguyen    15897
Emily Chen         14062
William Kim         8568
Olivia Tan          4519
Name: count, dtype: int64
Tenure Bucket
>90                30660
On Job Training    25523
31-60              11665
0-30               11318
61-90               6741
Name: count, dtype: int64
Agent Shift
Morning      41426
Evening      33677
Afternoon     5840
Split         3648
Night         1316
Name: count, dtype: int64
CSAT Score
5    59617
1    11230
4    11219
3     2558
2     1283
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# finding null values and unique value counts
null_values= round(df.isnull().sum() * 100 / len(df),2)
unique_values=df.nunique()
analysis_df = pd.DataFrame({'column_name': df.columns,"unique_values": unique_values,'null_values_%': null_values,"data_type":df.dtypes})
analysis_df.reset_index(drop=True,inplace=True)
analysis_df

                column_name  unique_values  null_values_% data_type
0                 Unique id          85907           0.00    object
1              channel_name              3           0.00    object
2                  category             12           0.00    object
3              Sub-category             57           0.00    object
4          Customer Remarks          18231          66.54    object
5                  Order_id          67675          21.22    object
6           order_date_time          13766          79.96    object
7         Issue_reported at          30923           0.00    object
8           issue_responded          30262           0.00    object
9      Survey_response_Date             31           0.00    object
10            Customer_City           1782          80.12    object
11         Product_category              9          79.98    object
12               Item_price           2789          79.97   float64
13  connected_handling_time            211          99.72   float64
14               Agent_name           1371           0.00    object
15               Supervisor             40           0.00    object
16                  Manager              6           0.00    object
17            Tenure Bucket              5           0.00    object
18              Agent Shift              5           0.00    object
19               CSAT Score              5           0.00     int64

### Cleaning Data

By looking above analysis we could notice categories such as Unique ID, Customer Remark and Order_ID wont be usefull for further analysis so we suppose to drope those Variables.

Some object variables looks to be like time stamp columns. So the data type need to get change for those variables.

Some Object and float dtype variables has filled with NAN. Those needs to get filled as per needs.

In [ ]:
#Dropping not needed variables
df1=df.drop(["Unique id","Customer Remarks","Order_id","order_date_time"],axis=1)
df1.sample(n=2)

,channel_name,category,Sub-category,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
42703,Inbound,Feedback,UnProfessional Behaviour,16/08/2023 14:31,16/08/2023 22:17,16-Aug-23,NaN,NaN,NaN,NaN,Rhonda Martin DVM,Wyatt Kim,Jennifer Nguyen,On Job Training,Morning,1
13092,Inbound,Order Related,Order status enquiry,06/08/2023 17:09,06/08/2023 19:54,06-Aug-23,NaN,NaN,NaN,NaN,Steven Buckley,Carter Park,Jennifer Nguyen,On Job Training,Evening,4

In [ ]:
#Replacing object dtype to timestamp dtype
col=['Issue_reported at','issue_responded','Survey_response_Date']
for i in col:
    df1[i]=pd.to_datetime(df1[i],dayfirst=True)
    print(i,": dtype =",df1[i].dtype)

Issue_reported at : dtype = datetime64[ns]
issue_responded : dtype = datetime64[ns]
Survey_response_Date : dtype = datetime64[ns]

In [ ]:
#Replacing null value according to needs
for i in df1.columns:
    if (df1[i].isnull().sum()>0 and df1[i].dtype=="object"):
        df1[i].fillna("Unknown",inplace=True)
        print(i, "Variable has object dtype, so it got Replace its null values to Unknown \n")
    elif (df1[i].isnull().sum()>0 and df1[i].dtype=="float64"):
        df1[i].fillna(df1[i].median(),inplace=True)
        print(i, "Variable has float dtype, so it got Replace its null values to columns median value \n")

In [ ]:
# finding null values and unique value counts
null_values1= round(df1.isnull().sum() * 100 / len(df),2)
unique_values1=df1.nunique()
analysis_df1 = pd.DataFrame({'column_name': df1.columns,"unique_values": unique_values1,'null_values_%': null_values1,"data_type":df1.dtypes})
analysis_df1.reset_index(drop=True,inplace=True)
analysis_df1

                column_name  unique_values  null_values_%       data_type
0              channel_name              3            0.0          object
1                  category             12            0.0          object
2              Sub-category             57            0.0          object
3         Issue_reported at          30923            0.0  datetime64[ns]
4           issue_responded          30262            0.0  datetime64[ns]
5      Survey_response_Date             31            0.0  datetime64[ns]
6             Customer_City           1783            0.0          object
7          Product_category             10            0.0          object
8                Item_price           2789            0.0         float64
9   connected_handling_time            211            0.0         float64
10               Agent_name           1371            0.0          object
11               Supervisor             40            0.0          object
12                  Manager              6            0.0          object
13            Tenure Bucket              5            0.0          object
14              Agent Shift              5            0.0          object
15               CSAT Score              5            0.0           int64

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   channel_name             85907 non-null  object
 1   category                 85907 non-null  object
 2   Sub-category             85907 non-null  object
 3   Issue_reported at        85907 non-null  datetime64[ns]
 4   issue_responded          85907 non-null  datetime64[ns]
 5   Survey_response_Date     85907 non-null  datetime64[ns]
 6   Customer_City            85907 non-null  object
 7   Product_category         85907 non-null  object
 8   Item_price               85907 non-null  float64
 9   connected_handling_time  85907 non-null  float64
 10  Agent_name               85907 non-null  object
 11  Supervisor               85907 non-null  object
 12  Manager                  85907 non-null  object
 13  Tenure Bucket            85907 non-null  object
 14  Agent Shift              85907 non-null  object
 15  CSAT Score               85907 non-null  int64
dtypes: datetime64[ns](3), float64(2), int64(1), object(10)
memory usage: 10.5+ MB

# Now the data looks clean, lets move further for analysis.

In [ ]:
df1=df1[["channel_name","Tenure Bucket","Item_price","CSAT Score"]]

In [ ]:
df1_=pd.get_dummies(df1,columns=["channel_name","Tenure Bucket"],drop_first=True)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# fit the scaler to the train set, it will learn the parameters
scaler.fit(df1_[["Item_price"]])

# transform train and test sets
df1_numerical_scaled = scaler.transform(df1_[["Item_price"]])
df1_numerical_scaled=pd.DataFrame(df1_numerical_scaled,columns=["Item_price"])

In [ ]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# # fit the scaler to the train set, it will learn the parameters
# scaler.fit(df1_[["Item_price","connected_handling_time"]])

# # transform train and test sets
# df1_numerical_scaled = scaler.transform(df1_[["Item_price","connected_handling_time"]])
# df1_numerical_scaled=pd.DataFrame(df1_numerical_scaled,columns=["Item_price","connected_handling_time"])

In [ ]:
df1_main=pd.concat([df1_,df1_numerical_scaled],axis=1).iloc[:,1:]
df1_main

,CSAT Score,channel_name_Inbound,channel_name_Outcall,Tenure Bucket_31-60,Tenure Bucket_61-90,Tenure Bucket_>90,Tenure Bucket_On Job Training,Item_price
0,5,False,True,False,False,False,True,-0.155302
1,5,False,True,False,False,True,False,-0.155302
2,5,True,False,False,False,False,True,-0.155302
3,5,True,False,False,False,True,False,-0.155302
4,5,True,False,False,False,False,False,-0.155302
...,...,...,...,...,...,...,...,...
85902,4,True,False,False,False,False,True,-0.155302
85903,5,True,False,False,False,True,False,-0.155302
85904,5,True,False,False,False,False,True,-0.155302
85905,4,True,False,False,False,True,False,-0.155302
85906,5,True,False,False,False,False,True,-0.155302

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

In [ ]:
X = df1_main.drop(columns=['CSAT Score'])
y = df1_main['CSAT Score'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, LeakyReLU

model = Sequential()

# Flatten layer
model.add(Flatten(input_shape=(7, 1)))
# First Dense layer with Leaky ReLU
model.add(Dense(128))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(128))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(128))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(128))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(128))
model.add(LeakyReLU(alpha=0.01))
# Second Dense layer with Leaky ReLU
# Output layer with softmax activation
model.add(Dense(6, activation='softmax'))

# Summary of the model
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 7)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu (LeakyReLU)         │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_1 (LeakyReLU)       │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_2 (LeakyReLU)       │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_3 (LeakyReLU)       │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ leaky_re_lu_4 (LeakyReLU)       │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │           774 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67,846 (265.02 KB)

 Trainable params: 67,846 (265.02 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adagrad',metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,y_train,epochs=25,validation_split=0.2)

Epoch 1/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6923 - loss: 0.9499 - val_accuracy: 0.6953 - val_loss: 0.9447
Epoch 2/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.6958 - loss: 0.9398 - val_accuracy: 0.6954 - val_loss: 0.9446
Epoch 3/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.6939 - loss: 0.9481 - val_accuracy: 0.6951 - val_loss: 0.9446
Epoch 4/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6927 - loss: 0.9512 - val_accuracy: 0.6954 - val_loss: 0.9445
Epoch 5/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6937 - loss: 0.9487 - val_accuracy: 0.6953 - val_loss: 0.9445
Epoch 6/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.6939 - loss: 0.9462 - val_accuracy: 0.6953 - val_loss: 0.9444
Epoch 7/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6943 - loss: 0.9473 - val_accuracy: 0.6953 - val_loss: 0.9443
Epoch 8/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.6953 - loss: 0.9417 - val_accuracy: 0.6953 - val_loss: 0.9443
Epoch 9/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6920 - loss: 0.9488 - val_accuracy: 0.6954 - val_loss: 0.9443
Epoch 10/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.6945 - loss: 0.9455 - val_accuracy: 0.6952 - val_loss: 0.9443
Epoch 11/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6935 - loss: 0.9451 - val_accuracy: 0.6954 - val_loss: 0.9442
Epoch 12/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.6921 - loss: 0.9519 - val_accuracy: 0.6954 - val_loss: 0.9442
Epoch 13/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.6951 - loss: 0.9465 - val_accuracy: 0.6953 - val_loss: 0.9443
Epoch 14/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6937 - loss: 0.9463 - val_accuracy: 0.6954 - val_loss: 0.9441
Epoch 15/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6912 - loss: 0.9518 - val_accuracy: 0.6954 - val_loss: 0.9440
Epoch 16/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6926 - loss: 0.9464 - val_accuracy: 0.6953 - val_loss: 0.9441
Epoch 17/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6909 - loss: 0.9516 - val_accuracy: 0.6955 - val_loss: 0.9440
Epoch 18/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6976 - loss: 0.9401 - val_accuracy: 0.6953 - val_loss: 0.9440
Epoch 19/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.6954 - loss: 0.9456 - val_accuracy: 0.6953 - val_loss: 0.9439
Epoch 20/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.6945 - loss: 0.9446 - val_accuracy: 0.6953 - val_loss: 0.9440
Epoch 21/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.6954 - loss: 0.9432 - val_accuracy: 0.6953 - val_loss: 0.9440
Epoch 22/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6934 - loss: 0.9463 - val_accuracy: 0.6955 - val_loss: 0.9438
Epoch 23/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.6920 - loss: 0.9503 - val_accuracy: 0.6955 - val_loss: 0.9438
Epoch 24/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.6971 - loss: 0.9419 - val_accuracy: 0.6955 - val_loss: 0.9439
Epoch 25/25
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6937 - loss: 0.9485 - val_accuracy: 0.6955 - val_loss: 0.9437

In [ ]:
y_prob = model.predict(X_test)

537/537 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [ ]:
y_pred = y_prob.argmax(axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6911884530322431

In [ ]:
!pip3 install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.11/dist-packages (5.28.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.9.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.115.12)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.11/dist-packages (from gradio) (0.5.0)
Requirement already satisfied: gradio-client==1.10.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (1.10.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.30.2)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.2.1)
Requirement already satisfied: pydantic<2.12,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.11.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.11.7)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.46.2)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.13.2)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.34.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.10.0->gradio) (2025.3.2)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.10.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.4.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.4.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [ ]:
# Define the prediction function
import gradio as gr
def predict(feature1, feature2, feature3, feature4, feature5, feature6, feature7):
    # Convert "True"/"False" to 1/0
    features_np = [
        1 if feature1 == "True" else 0,
        1 if feature2 == "True" else 0,
        1 if feature3 == "True" else 0,
        1 if feature4 == "True" else 0,
        1 if feature5 == "True" else 0,
        1 if feature6 == "True" else 0,

        #float(feature7)  # Convert text input to float
    ]
    feature7 = np.array([[feature7]])
    feature7= scaler.transform(feature7)[0, 0]

    features_np = features_np + [feature7]
    features_np = np.array(features_np).reshape(1, -1)

    # Make prediction
    prediction = model.predict(features_np)
    predicted_class = np.argmax(prediction, axis=1)
    return str(predicted_class[0])  # Convert to string for display

# Create the Gradio interface
interface = gr.Interface(
    fn=predict,  # The function to call for prediction
    inputs=[
        gr.Radio(choices=["True", "False"], label="channel_name_Inbound"),
        gr.Radio(choices=["True", "False"], label="channel_name_Outcall"),
        gr.Radio(choices=["True", "False"], label="Tenure Bucket_31-60"),
        gr.Radio(choices=["True", "False"], label="Tenure Bucket_61-90"),
        gr.Radio(choices=["True", "False"], label="Tenure Bucket_>90"),
        gr.Radio(choices=["True", "False"], label="Tenure Bucket_On Job Training"),
        gr.Textbox(label="Item_price", type="text")  # Textbox for numerical input
    ],
    outputs=gr.Textbox(label="CSAT Score"),
    title="eCommerce Customer Service Satisfaction App",
    description="Please enter all the values to predict CSAT Score"
)

# Launch the interface
interface.launch()

It looks like you are running Gradio on a hosted a Jupyter notebook. For the Gradio app to work, sharing must be enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://6fb5428481ce9533bc.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)